### ISSUE TITLE
Unable to start raspardas acquisition if netid in EEPROM doesn't fit netid in settings.py

### ISSUE THREAD

**Issue by bastinc** [UMONS-GFA/ardas#100]
1) Only one ardas connected: should call 999 and check if there is a reply and if the reply matches settings.
2) Several ardas are connected ??

**Comment by kaufmanno** [comment]
This is intended behavior for now. Either 
A- change settings.py to fit EEPROM then change ID in both EEPROM with the #ZR command and settings.py file
B- reset EEPROM and set id to 255.
