### ISSUE TITLE
date no synced in raspardas.py

### ISSUE THREAD

**Issue by bastinc** [UMONS-GFA/ardas#52]

**Comment by kaufmanno** [comment]
Here is a code snippet to get a datetime from a pool of NTP servers and generate the ardas command to set the new date...

import ntplib
import datetime
from time import ctime
c = ntplib.NTPClient()
now = datetime.datetime.utcfromtimestamp(c.request('europe.pool.ntp.org').tx_time)
message = print('#SD %04d %02d %02d %02d %02d %02d' %(now.year, now.month, now.day, now.hour, now.minute, now.second))

**Comment by bastinc** [comment]
implement a new cron task in python:
* Pause acquisition with #PA command #71
* to sync date (code snippet) 
* to  change file with #CF command

**Comment by kaufmanno** [comment]
If the NTP server is not available, the raspberry pi clock should be set from the ardas RTC !
