### ISSUE TITLE
Push annotations in InfluxDB

### ISSUE THREAD

**Issue by bastinc** [UMONS-GFA/ardas#68]
Annotations send by raspardas:
* set date
* set config
* CRC error

See  http://docs.grafana.org/reference/annotations/

**Comment by kaufmanno** [comment]
It would be a good practice to ask for a 'restart' tagged annotation at each restart (but do not block automatic restart with a default value such as 'reboot' for tag 'restart') and to allow annotations trough a master connection (telnet)

for inserting annotations see also https://maxchadwick.xyz/blog/grafana-influxdb-annotations

**Comment by kaufmanno** [comment]
It turns out that there are two types of annotations:
- the grafana native (including the interactive annotations created with a ctrl + left mouse button) 
- the annotations based on another data source such as InfluxDB and retrieved via a query

**Comment by kaufmanno** [comment]
Influxdb annotations implemented in v1.1.3.1
