### ISSUE TITLE
Documentation hosting or publishing

### ISSUE THREAD

**Issue by kaufmanno** [UMONS-GFA/ardas#78]
It would be nice to host or publish the release documentation 'à la readthedocs' so that it could be accessible on a website (and add the link in the Github project).

**Comment by kaufmanno** [comment]
Should probably recycle parts of what @bastinc wrote for pidas...

**Comment by bastinc** [comment]
@kaufmanno The doc is already up on readthedocs.
The badge on the README page is a link to the doc.
[http://ardas.readthedocs.io/en/latest/](http://ardas.readthedocs.io/en/latest/)
