### ISSUE TITLE
Pipenv doesn't work well on raspberry pi

### ISSUE THREAD

**Issue by bastinc** [UMONS-GFA/ardas#92]
We need to fix packages versions in a requirement.txt

**Comment by bastinc** [comment]
We should try to increase the timeout
https://stackoverflow.com/questions/50382837/pipenv-install-timing-out-on-rpi

export PIPENV_TIMEOUT=500

**Comment by kaufmanno** [comment]
We chose to avoid using pipenv on the raspberry pi and rather use pip3 with a requirement.txt file generated with pip3 freeze in the virtual environment running on the developer machine
